services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: coordinator\n"\
          "    dns:\n"\
          "      - coordinator\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-blue01\n"\
          "    dns:\n"\
          "      - es-blue01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-blue02\n"\
          "    dns:\n"\
          "      - es-blue02\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-blue03\n"\
          "    dns:\n"\
          "      - es-blue03\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-green01\n"\
          "    dns:\n"\
          "      - es-green01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-green02\n"\
          "    dns:\n"\
          "      - es-green02\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: es-green03\n"\
          "    dns:\n"\
          "      - es-green03\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://coordinator:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://coordinator:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/coordinator/coordinator.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  coordinator:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - coordinator:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=coordinator
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=coordinator,es-blue01,es-blue02,es-blue03
      - discovery.seed_hosts=es-blue01,es-blue02,es-blue03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/coordinator/coordinator.key
      - xpack.security.http.ssl.certificate=certs/coordinator/coordinator.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/coordinator/coordinator.key
      - xpack.security.transport.ssl.certificate=certs/coordinator/coordinator.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  es-blue01:
    depends_on:
      coordinator:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-blue01:/usr/share/elasticsearch/data
    environment:
      - node.name=es-blue01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-blue01,es-blue02,es-blue03,coordinator
      - discovery.seed_hosts=es-blue02,es-blue03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-blue01/es-blue01.key
      - xpack.security.http.ssl.certificate=certs/es-blue01/es-blue01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-blue01/es-blue01.key
      - xpack.security.transport.ssl.certificate=certs/es-blue01/es-blue01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-blue02:
    depends_on:
      - es-blue01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-blue02:/usr/share/elasticsearch/data
    environment:
      - node.name=es-blue02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-blue01,es-blue02,es-blue03,coordinator
      - discovery.seed_hosts=es-blue01,es-blue03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-blue02/es-blue02.key
      - xpack.security.http.ssl.certificate=certs/es-blue02/es-blue02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-blue02/es-blue02.key
      - xpack.security.transport.ssl.certificate=certs/es-blue02/es-blue02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-blue03:
    depends_on:
      - es-blue02
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-blue03:/usr/share/elasticsearch/data
    environment:
      - node.name=es-blue03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es-blue01,es-blue02,es-blue03,coordinator
      - discovery.seed_hosts=es-blue01,es-blue02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-blue03/es-blue03.key
      - xpack.security.http.ssl.certificate=certs/es-blue03/es-blue03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-blue03/es-blue03.key
      - xpack.security.transport.ssl.certificate=certs/es-blue03/es-blue03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120




  es-green01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_GREEN_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-green01:/usr/share/elasticsearch/data
    environment:
      - node.name=es-green01
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=coordinator,es-green02,es-green03
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-green01/es-green01.key
      - xpack.security.http.ssl.certificate=certs/es-green01/es-green01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-green01/es-green01.key
      - xpack.security.transport.ssl.certificate=certs/es-green01/es-green01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-green02:
    depends_on:
      - es-green01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_GREEN_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-green02:/usr/share/elasticsearch/data
    environment:
      - node.name=es-green02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=coordinator,es-green01,es-green03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-green02/es-green02.key
      - xpack.security.http.ssl.certificate=certs/es-green02/es-green02.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-green02/es-green02.key
      - xpack.security.transport.ssl.certificate=certs/es-green02/es-green02.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  es-green03:
    depends_on:
      - es-green02
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_GREEN_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata-green03:/usr/share/elasticsearch/data
    environment:
      - node.name=es-green03
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=coordinator,es-green01,es-green02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es-green03/es-green03.key
      - xpack.security.http.ssl.certificate=certs/es-green03/es-green03.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es-green03/es-green03.key
      - xpack.security.transport.ssl.certificate=certs/es-green03/es-green03.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://coordinator:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


volumes:
  certs:
    driver: local
  coordinator:
    driver: local
  esdata-blue01:
    driver: local
  esdata-blue02:
    driver: local
  esdata-blue03:
    driver: local
  esdata-green01:
    driver: local
  esdata-green02:
    driver: local
  esdata-green03:
    driver: local
  kibanadata:
    driver: local