apiVersion: v1
kind: Service
metadata:
  name: elastic-nodes-http
  namespace: fastcampus
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: "elasticsearch"
---
apiVersion: v1
kind: Service
metadata:
  name: master-nodes-http
  namespace: fastcampus
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: "elasticsearch"
    elasticsearch.k8s.elastic.co/node-master: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: data-nodes-http
  namespace: fastcampus
spec:
  ports:
    - name: https
      port: 9200
      targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: "elasticsearch"
    elasticsearch.k8s.elastic.co/node-data: "true"