apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: fastcampus
spec:
  version: 8.12.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    monitoring.ui.ccs.enabled: false
    monitoring.ui.elasticsearch:
      hosts:
        - "https://m-elasticsearch-es-http.fastcampus.svc:9200"
      ssl:
        certificateAuthorities: /usr/share/kibana/config/m-elasticsearch-certs/ca.crt
        verificationMode: certificate
  podTemplate:
    spec:
      initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: [ 'sh', '-c',  'sysctl -w vm.swappiness=1; sysctl -w vm.max_map_count=262144;' ]
      containers:
        - name: kibana
          volumeMounts:
            - name: m-elasticsearch-certs
              mountPath: /usr/share/kibana/config/m-elasticsearch-certs
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              memory: 2Gi
      volumes:
        - name: m-elasticsearch-certs
          secret:
            secretName: m-elasticsearch-es-http-certs-public