apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: m-elasticsearch
  namespace: fastcampus
spec:
  version: 8.12.2
  nodeSets:
    - name: monitoring
      count: 3
      config:
        node.roles: [ "master", "data", "ingest", "remote_cluster_client"]
        bootstrap.memory_lock: true
        xpack.ml.enabled: false
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: [ 'sh', '-c',  'sysctl -w vm.swappiness=1; sysctl -w vm.max_map_count=262144;' ]
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 1
                  memory: 2Gi
                limits:
                  memory: 2Gi
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms1g -Xmx1g
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2